create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  full_name text not null default '',
  birth_year text not null default '',
  phone text not null default '',
  email text not null default '',
  city text not null default '',
  occupation text not null default '',
  identity_text text not null default '',
  motivation text not null default '',
  story text not null default '',
  strength text not null default '',
  expectation_json text not null default '[]',
  availability text not null default '',
  truth_confirmation boolean not null default false,
  media_consent boolean not null default false,
  consent boolean not null default false,
  hidden boolean not null default false,
  submitted_at text not null default ''
);

alter table public.submissions add column if not exists full_name text;
alter table public.submissions add column if not exists birth_year text;
alter table public.submissions add column if not exists phone text;
alter table public.submissions add column if not exists email text;
alter table public.submissions add column if not exists city text;
alter table public.submissions add column if not exists occupation text;
alter table public.submissions add column if not exists identity_text text;
alter table public.submissions add column if not exists motivation text;
alter table public.submissions add column if not exists story text;
alter table public.submissions add column if not exists strength text;
alter table public.submissions add column if not exists expectation_json text;
alter table public.submissions add column if not exists availability text;
alter table public.submissions add column if not exists truth_confirmation boolean;
alter table public.submissions add column if not exists media_consent boolean;
alter table public.submissions add column if not exists consent boolean;
alter table public.submissions add column if not exists hidden boolean;
alter table public.submissions add column if not exists submitted_at text;
alter table public.submissions drop column if exists photo_data_url;
alter table public.submissions drop column if exists photo_file_name;

update public.submissions
set
  full_name = coalesce(full_name, ''),
  birth_year = coalesce(birth_year, ''),
  phone = coalesce(phone, ''),
  email = coalesce(email, ''),
  city = coalesce(city, ''),
  occupation = coalesce(occupation, ''),
  identity_text = coalesce(identity_text, ''),
  motivation = coalesce(motivation, ''),
  story = coalesce(story, ''),
  strength = coalesce(strength, ''),
  expectation_json = case
    when expectation_json is null or btrim(expectation_json) = '' then '[]'
    else expectation_json
  end,
  availability = coalesce(availability, ''),
  truth_confirmation = coalesce(truth_confirmation, consent, false),
  media_consent = coalesce(media_consent, consent, false),
  consent = coalesce(consent, false),
  hidden = coalesce(hidden, false),
  submitted_at = case
    when submitted_at is null or btrim(submitted_at) = '' then replace((now() at time zone 'utc')::text, ' ', 'T') || 'Z'
    else submitted_at
  end
where
  full_name is null
  or birth_year is null
  or phone is null
  or email is null
  or city is null
  or occupation is null
  or identity_text is null
  or motivation is null
  or story is null
  or strength is null
  or expectation_json is null
  or btrim(expectation_json) = ''
  or availability is null
  or truth_confirmation is null
  or media_consent is null
  or consent is null
  or hidden is null
  or submitted_at is null
  or btrim(submitted_at) = '';

alter table public.submissions alter column full_name set default '';
alter table public.submissions alter column birth_year set default '';
alter table public.submissions alter column phone set default '';
alter table public.submissions alter column email set default '';
alter table public.submissions alter column city set default '';
alter table public.submissions alter column occupation set default '';
alter table public.submissions alter column identity_text set default '';
alter table public.submissions alter column motivation set default '';
alter table public.submissions alter column story set default '';
alter table public.submissions alter column strength set default '';
alter table public.submissions alter column expectation_json set default '[]';
alter table public.submissions alter column availability set default '';
alter table public.submissions alter column truth_confirmation set default false;
alter table public.submissions alter column media_consent set default false;
alter table public.submissions alter column consent set default false;
alter table public.submissions alter column hidden set default false;
alter table public.submissions alter column submitted_at set default '';

alter table public.submissions alter column full_name set not null;
alter table public.submissions alter column birth_year set not null;
alter table public.submissions alter column phone set not null;
alter table public.submissions alter column email set not null;
alter table public.submissions alter column city set not null;
alter table public.submissions alter column occupation set not null;
alter table public.submissions alter column identity_text set not null;
alter table public.submissions alter column motivation set not null;
alter table public.submissions alter column story set not null;
alter table public.submissions alter column strength set not null;
alter table public.submissions alter column expectation_json set not null;
alter table public.submissions alter column availability set not null;
alter table public.submissions alter column truth_confirmation set not null;
alter table public.submissions alter column media_consent set not null;
alter table public.submissions alter column consent set not null;
alter table public.submissions alter column hidden set not null;
alter table public.submissions alter column submitted_at set not null;

create index if not exists submissions_hidden_idx on public.submissions(hidden);
create index if not exists submissions_submitted_at_idx on public.submissions(submitted_at);
create index if not exists submissions_full_name_idx on public.submissions(full_name);

comment on column public.submissions.expectation_json is 'JSON array stored as text for multi-part expectation answers.';

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  subscription_json text not null default '{}',
  user_agent text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

alter table public.push_subscriptions add column if not exists endpoint text;
alter table public.push_subscriptions add column if not exists subscription_json text;
alter table public.push_subscriptions add column if not exists user_agent text;
alter table public.push_subscriptions add column if not exists active boolean;
alter table public.push_subscriptions add column if not exists created_at timestamptz;
alter table public.push_subscriptions add column if not exists updated_at timestamptz;
alter table public.push_subscriptions add column if not exists last_seen timestamptz;

update public.push_subscriptions
set
  endpoint = coalesce(endpoint, ''),
  subscription_json = case
    when subscription_json is null or btrim(subscription_json) = '' then '{}'
    else subscription_json
  end,
  user_agent = coalesce(user_agent, ''),
  active = coalesce(active, true),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now()),
  last_seen = coalesce(last_seen, now())
where
  endpoint is null
  or subscription_json is null
  or btrim(subscription_json) = ''
  or user_agent is null
  or active is null
  or created_at is null
  or updated_at is null
  or last_seen is null;

alter table public.push_subscriptions alter column endpoint set default '';
alter table public.push_subscriptions alter column subscription_json set default '{}';
alter table public.push_subscriptions alter column user_agent set default '';
alter table public.push_subscriptions alter column active set default true;
alter table public.push_subscriptions alter column created_at set default now();
alter table public.push_subscriptions alter column updated_at set default now();
alter table public.push_subscriptions alter column last_seen set default now();

alter table public.push_subscriptions alter column endpoint set not null;
alter table public.push_subscriptions alter column subscription_json set not null;
alter table public.push_subscriptions alter column user_agent set not null;
alter table public.push_subscriptions alter column active set not null;
alter table public.push_subscriptions alter column created_at set not null;
alter table public.push_subscriptions alter column updated_at set not null;
alter table public.push_subscriptions alter column last_seen set not null;

create unique index if not exists push_subscriptions_endpoint_uidx on public.push_subscriptions(endpoint);
create index if not exists push_subscriptions_active_idx on public.push_subscriptions(active);
