create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  birth_year text not null,
  phone text not null,
  email text not null,
  city text not null,
  occupation text not null,
  identity_text text not null default '',
  motivation text not null,
  story text not null,
  strength text not null,
  expectation_json text not null default '[]',
  availability text not null,
  consent boolean not null default false,
  photo_data_url text not null default '',
  photo_file_name text not null default '',
  hidden boolean not null default false,
  submitted_at text not null
);

alter table public.submissions add column if not exists photo_data_url text not null default '';
alter table public.submissions add column if not exists photo_file_name text not null default '';

create index if not exists submissions_hidden_idx on public.submissions(hidden);
create index if not exists submissions_submitted_at_idx on public.submissions(submitted_at);
